site_name: Notes From Beyond
site_author: Anubhav Singhal
site_description: concepts, quick reads, notes, etc.

repo_name: data_engineering
repo_url: https://github.com/anubhav-data1/data_engineering
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 Anubhav Singhal

theme:
  name: material
  language: en

nav:
  - Home: home/start.md
  - Cloud: 
      - AWS:
        - Service: Cloud/AWS/services.md
        - Databases: Cloud/AWS/databases.md
        - Disaster Recovery: Cloud/AWS/disasterrecovery.md
        - Migratation: Cloud/AWS/migrataion.md
        - Gateway: Cloud/AWS/gateway.md
        - Logs: Cloud/AWS/logs.md
  - Linux: Random/linux.md
  - Photography: Photography/Basic.md